# Generated by Django 4.2.30 on 2026-05-02 06:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='smtp_password',
            field=models.CharField(default=api.models.generate_smtp_password, max_length=50),
        ),
        migrations.AddField(
            model_name='inbox',
            name='smtp_username',
            field=models.CharField(default=api.models.generate_smtp_username, max_length=50, unique=True),
        ),
    ]
